/***
 Automatic generated by gen-mucode.c.bash
***/

#include "cpu.h"

void do_ADC(struct _6510_cpu* cpu, char *mem){
}
void do_AND(struct _6510_cpu* cpu, char *mem){
}
void do_ASL(struct _6510_cpu* cpu, char *mem){
}
void do_BCC(struct _6510_cpu* cpu, char *mem){
}
void do_BCS(struct _6510_cpu* cpu, char *mem){
}
void do_BEQ(struct _6510_cpu* cpu, char *mem){
}
void do_BIT(struct _6510_cpu* cpu, char *mem){
}
void do_BMI(struct _6510_cpu* cpu, char *mem){
}
void do_BNE(struct _6510_cpu* cpu, char *mem){
}
void do_BPL(struct _6510_cpu* cpu, char *mem){
}
void do_BRK(struct _6510_cpu* cpu, char *mem){
}
void do_BVC(struct _6510_cpu* cpu, char *mem){
}
void do_BVS(struct _6510_cpu* cpu, char *mem){
}
void do_CLC(struct _6510_cpu* cpu, char *mem){
}
void do_CLD(struct _6510_cpu* cpu, char *mem){
}
void do_CLI(struct _6510_cpu* cpu, char *mem){
}
void do_CLV(struct _6510_cpu* cpu, char *mem){
}
void do_CMP(struct _6510_cpu* cpu, char *mem){
}
void do_CPX(struct _6510_cpu* cpu, char *mem){
}
void do_CPY(struct _6510_cpu* cpu, char *mem){
}
void do_DEC(struct _6510_cpu* cpu, char *mem){
}
void do_DEX(struct _6510_cpu* cpu, char *mem){
}
void do_DEY(struct _6510_cpu* cpu, char *mem){
}
void do_EOR(struct _6510_cpu* cpu, char *mem){
}
void do_INC(struct _6510_cpu* cpu, char *mem){
}
void do_INX(struct _6510_cpu* cpu, char *mem){
}
void do_INY(struct _6510_cpu* cpu, char *mem){
}
void do_JMP(struct _6510_cpu* cpu, char *mem){
}
void do_JSR(struct _6510_cpu* cpu, char *mem){
}
void do_LDA(struct _6510_cpu* cpu, char *mem){
}
void do_LDX(struct _6510_cpu* cpu, char *mem){
}
void do_LDY(struct _6510_cpu* cpu, char *mem){
}
void do_LSR(struct _6510_cpu* cpu, char *mem){
}
void do_NOP(struct _6510_cpu* cpu, char *mem){
}
void do_ORA(struct _6510_cpu* cpu, char *mem){
}
void do_PHA(struct _6510_cpu* cpu, char *mem){
}
void do_PHP(struct _6510_cpu* cpu, char *mem){
}
void do_PLA(struct _6510_cpu* cpu, char *mem){
}
void do_PLP(struct _6510_cpu* cpu, char *mem){
}
void do_ROL(struct _6510_cpu* cpu, char *mem){
}
void do_ROR(struct _6510_cpu* cpu, char *mem){
}
void do_RTI(struct _6510_cpu* cpu, char *mem){
}
void do_RTS(struct _6510_cpu* cpu, char *mem){
}
void do_SBC(struct _6510_cpu* cpu, char *mem){
}
void do_SEC(struct _6510_cpu* cpu, char *mem){
}
void do_SED(struct _6510_cpu* cpu, char *mem){
}
void do_SEI(struct _6510_cpu* cpu, char *mem){
}
void do_STA(struct _6510_cpu* cpu, char *mem){
}
void do_STX(struct _6510_cpu* cpu, char *mem){
}
void do_STY(struct _6510_cpu* cpu, char *mem){
}
void do_TAX(struct _6510_cpu* cpu, char *mem){
}
void do_TAY(struct _6510_cpu* cpu, char *mem){
}
void do_TSX(struct _6510_cpu* cpu, char *mem){
}
void do_TXA(struct _6510_cpu* cpu, char *mem){
}
void do_TXS(struct _6510_cpu* cpu, char *mem){
}
void do_TYA(struct _6510_cpu* cpu, char *mem){
}
/*
  opname:  BRK
  opcode:  0x00 
  example: BRK 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :--1-1--
  bytes: 1 
  
*/

void cpu_6502_BRK_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_BRK(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x01 
  example: ORA ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_ORA_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x05 
  example: ORA $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_ORA_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ASL
  opcode:  0x06 
  example: ASL $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ASL_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_ASL(cpu, mem[eadr]);


}


/*
  opname:  PHP
  opcode:  0x08 
  example: PHP 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-------
  bytes: 1 
  
*/

void cpu_6502_PHP_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_PHP(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x09 
  example: ORA #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_ORA_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ASL
  opcode:  0x0A 
  example: ASL 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----**
  bytes: 1 
  
*/

void cpu_6502_ASL_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_ASL(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x0D 
  example: ORA $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_ORA_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ASL
  opcode:  0x0E 
  example: ASL $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ASL_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_ASL(cpu, mem[eadr]);


}


/*
  opname:  BPL
  opcode:  0x10 
  example: BPL $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BPL_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BPL(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x11 
  example: ORA ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_ORA_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x15 
  example: ORA $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_ORA_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ASL
  opcode:  0x16 
  example: ASL $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ASL_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_ASL(cpu, mem[eadr]);


}


/*
  opname:  CLC
  opcode:  0x18 
  example: CLC 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :------0
  bytes: 1 
  
*/

void cpu_6502_CLC_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_CLC(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x19 
  example: ORA $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_ORA_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ORA
  opcode:  0x1D 
  example: ORA $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_ORA_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_ORA(cpu, mem[eadr]);


}


/*
  opname:  ASL
  opcode:  0x1E 
  example: ASL $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ASL_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_ASL(cpu, mem[eadr]);


}


/*
  opname:  JSR
  opcode:  0x20 
  example: JSR $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_JSR_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_JSR(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x21 
  example: AND ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_AND_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  BIT
  opcode:  0x24 
  example: BIT $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :**---*-
  bytes: 2 
  
*/

void cpu_6502_BIT_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_BIT(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x25 
  example: AND $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_AND_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  ROL
  opcode:  0x26 
  example: ROL $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ROL_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_ROL(cpu, mem[eadr]);


}


/*
  opname:  PLP
  opcode:  0x28 
  example: PLP 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :**-****
  bytes: 1 
  
*/

void cpu_6502_PLP_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_PLP(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x29 
  example: AND #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_AND_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  ROL
  opcode:  0x2A 
  example: ROL 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----**
  bytes: 1 
  
*/

void cpu_6502_ROL_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_ROL(cpu, mem[eadr]);


}


/*
  opname:  BIT
  opcode:  0x2C 
  example: BIT $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :**---*-
  bytes: 3 
  
*/

void cpu_6502_BIT_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_BIT(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x2D 
  example: AND $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_AND_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  ROL
  opcode:  0x2E 
  example: ROL $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ROL_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_ROL(cpu, mem[eadr]);


}


/*
  opname:  BMI
  opcode:  0x30 
  example: BMI $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BMI_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BMI(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x31 
  example: AND ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_AND_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x35 
  example: AND $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_AND_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  ROL
  opcode:  0x36 
  example: ROL $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ROL_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_ROL(cpu, mem[eadr]);


}


/*
  opname:  SEC
  opcode:  0x38 
  example: SEC 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :------1
  bytes: 1 
  
*/

void cpu_6502_SEC_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_SEC(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x39 
  example: AND $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_AND_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  AND
  opcode:  0x3D 
  example: AND $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_AND_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_AND(cpu, mem[eadr]);


}


/*
  opname:  ROL
  opcode:  0x3E 
  example: ROL $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ROL_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_ROL(cpu, mem[eadr]);


}


/*
  opname:  RTI
  opcode:  0x40 
  example: RTI 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :**-****
  bytes: 1 
  
*/

void cpu_6502_RTI_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_RTI(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x41 
  example: EOR ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_EOR_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x45 
  example: EOR $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_EOR_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  LSR
  opcode:  0x46 
  example: LSR $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_LSR_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_LSR(cpu, mem[eadr]);


}


/*
  opname:  PHA
  opcode:  0x48 
  example: PHA 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-------
  bytes: 1 
  
*/

void cpu_6502_PHA_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_PHA(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x49 
  example: EOR #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_EOR_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  LSR
  opcode:  0x4A 
  example: LSR 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----**
  bytes: 1 
  
*/

void cpu_6502_LSR_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_LSR(cpu, mem[eadr]);


}


/*
  opname:  JMP
  opcode:  0x4C 
  example: JMP $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_JMP_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_JMP(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x4D 
  example: EOR $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_EOR_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  LSR
  opcode:  0x4E 
  example: LSR $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_LSR_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_LSR(cpu, mem[eadr]);


}


/*
  opname:  BVC
  opcode:  0x50 
  example: BVC $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BVC_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BVC(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x51 
  example: EOR ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_EOR_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x55 
  example: EOR $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_EOR_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  LSR
  opcode:  0x56 
  example: LSR $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_LSR_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_LSR(cpu, mem[eadr]);


}


/*
  opname:  CLI
  opcode:  0x58 
  example: CLI 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :----0--
  bytes: 1 
  
*/

void cpu_6502_CLI_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_CLI(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x59 
  example: EOR $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_EOR_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  EOR
  opcode:  0x5D 
  example: EOR $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_EOR_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_EOR(cpu, mem[eadr]);


}


/*
  opname:  LSR
  opcode:  0x5E 
  example: LSR $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_LSR_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_LSR(cpu, mem[eadr]);


}


/*
  opname:  RTS
  opcode:  0x60 
  example: RTS 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-------
  bytes: 1 
  
*/

void cpu_6502_RTS_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_RTS(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x61 
  example: ADC ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_ADC_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x65 
  example: ADC $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_ADC_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ROR
  opcode:  0x66 
  example: ROR $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ROR_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_ROR(cpu, mem[eadr]);


}


/*
  opname:  PLA
  opcode:  0x68 
  example: PLA 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_PLA_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_PLA(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x69 
  example: ADC #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_ADC_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ROR
  opcode:  0x6A 
  example: ROR 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----**
  bytes: 1 
  
*/

void cpu_6502_ROR_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_ROR(cpu, mem[eadr]);


}


/*
  opname:  JMP
  opcode:  0x6C 
  example: JMP $ABCD
  adr:  indirect; indirection via zp address; ea = mem[zpadr+1]|mem[zpadr]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_JMP_ind(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = ind_adr_mode(cpu, mem);
  do_JMP(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x6D 
  example: ADC $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_ADC_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ROR
  opcode:  0x6E 
  example: ROR $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ROR_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_ROR(cpu, mem[eadr]);


}


/*
  opname:  BVS
  opcode:  0x70 
  example: BVS $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BVS_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BVS(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x71 
  example: ADC ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_ADC_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x75 
  example: ADC $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_ADC_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ROR
  opcode:  0x76 
  example: ROR $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_ROR_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_ROR(cpu, mem[eadr]);


}


/*
  opname:  SEI
  opcode:  0x78 
  example: SEI 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :----1--
  bytes: 1 
  
*/

void cpu_6502_SEI_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_SEI(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x79 
  example: ADC $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_ADC_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ADC
  opcode:  0x7D 
  example: ADC $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_ADC_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_ADC(cpu, mem[eadr]);


}


/*
  opname:  ROR
  opcode:  0x7E 
  example: ROR $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_ROR_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_ROR(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x81 
  example: STA ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STA_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  STY
  opcode:  0x84 
  example: STY $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STY_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_STY(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x85 
  example: STA $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STA_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  STX
  opcode:  0x86 
  example: STX $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STX_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_STX(cpu, mem[eadr]);


}


/*
  opname:  DEY
  opcode:  0x88 
  example: DEY 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_DEY_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_DEY(cpu, mem[eadr]);


}


/*
  opname:  TXA
  opcode:  0x8A 
  example: TXA 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_TXA_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TXA(cpu, mem[eadr]);


}


/*
  opname:  STY
  opcode:  0x8C 
  example: STY $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_STY_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_STY(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x8D 
  example: STA $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_STA_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  STX
  opcode:  0x8E 
  example: STX $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_STX_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_STX(cpu, mem[eadr]);


}


/*
  opname:  BCC
  opcode:  0x90 
  example: BCC $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BCC_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BCC(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x91 
  example: STA ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STA_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  STY
  opcode:  0x94 
  example: STY $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STY_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_STY(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x95 
  example: STA $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STA_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  STX
  opcode:  0x96 
  example: STX $AB,X
  adr:  zero page with index register Y; ea = zpadr+Y
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_STX_zpy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpy_adr_mode(cpu, mem);
  do_STX(cpu, mem[eadr]);


}


/*
  opname:  TYA
  opcode:  0x98 
  example: TYA 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_TYA_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TYA(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x99 
  example: STA $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_STA_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  TXS
  opcode:  0x9A 
  example: TXS 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-------
  bytes: 1 
  
*/

void cpu_6502_TXS_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TXS(cpu, mem[eadr]);


}


/*
  opname:  STA
  opcode:  0x9D 
  example: STA $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :-------
  bytes: 3 
  
*/

void cpu_6502_STA_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_STA(cpu, mem[eadr]);


}


/*
  opname:  LDY
  opcode:  0xA0 
  example: LDY #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDY_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_LDY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xA1 
  example: LDA ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDA_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDX
  opcode:  0xA2 
  example: LDX #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDX_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_LDX(cpu, mem[eadr]);


}


/*
  opname:  LDY
  opcode:  0xA4 
  example: LDY $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDY_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_LDY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xA5 
  example: LDA $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDA_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDX
  opcode:  0xA6 
  example: LDX $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDX_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_LDX(cpu, mem[eadr]);


}


/*
  opname:  TAY
  opcode:  0xA8 
  example: TAY 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_TAY_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TAY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xA9 
  example: LDA #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDA_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  TAX
  opcode:  0xAA 
  example: TAX 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_TAX_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TAX(cpu, mem[eadr]);


}


/*
  opname:  LDY
  opcode:  0xAC 
  example: LDY $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDY_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_LDY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xAD 
  example: LDA $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDA_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDX
  opcode:  0xAE 
  example: LDX $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDX_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_LDX(cpu, mem[eadr]);


}


/*
  opname:  BCS
  opcode:  0xB0 
  example: BCS $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BCS_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BCS(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xB1 
  example: LDA ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDA_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDY
  opcode:  0xB4 
  example: LDY $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDY_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_LDY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xB5 
  example: LDA $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDA_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDX
  opcode:  0xB6 
  example: LDX $AB,X
  adr:  zero page with index register Y; ea = zpadr+Y
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_LDX_zpy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpy_adr_mode(cpu, mem);
  do_LDX(cpu, mem[eadr]);


}


/*
  opname:  CLV
  opcode:  0xB8 
  example: CLV 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-0-----
  bytes: 1 
  
*/

void cpu_6502_CLV_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_CLV(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xB9 
  example: LDA $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDA_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  TSX
  opcode:  0xBA 
  example: TSX 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_TSX_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_TSX(cpu, mem[eadr]);


}


/*
  opname:  LDY
  opcode:  0xBC 
  example: LDY $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDY_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_LDY(cpu, mem[eadr]);


}


/*
  opname:  LDA
  opcode:  0xBD 
  example: LDA $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDA_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_LDA(cpu, mem[eadr]);


}


/*
  opname:  LDX
  opcode:  0xBE 
  example: LDX $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_LDX_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_LDX(cpu, mem[eadr]);


}


/*
  opname:  CPY
  opcode:  0xC0 
  example: CPY #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CPY_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_CPY(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xC1 
  example: CMP ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CMP_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  CPY
  opcode:  0xC4 
  example: CPY $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CPY_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_CPY(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xC5 
  example: CMP $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CMP_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  DEC
  opcode:  0xC6 
  example: DEC $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_DEC_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_DEC(cpu, mem[eadr]);


}


/*
  opname:  INY
  opcode:  0xC8 
  example: INY 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_INY_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_INY(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xC9 
  example: CMP #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CMP_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  DEX
  opcode:  0xCA 
  example: DEX 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_DEX_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_DEX(cpu, mem[eadr]);


}


/*
  opname:  CPY
  opcode:  0xCC 
  example: CPY $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_CPY_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_CPY(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xCD 
  example: CMP $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_CMP_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  DEC
  opcode:  0xCE 
  example: DEC $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_DEC_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_DEC(cpu, mem[eadr]);


}


/*
  opname:  BNE
  opcode:  0xD0 
  example: BNE $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BNE_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BNE(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xD1 
  example: CMP ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CMP_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xD5 
  example: CMP $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CMP_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  DEC
  opcode:  0xD6 
  example: DEC $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_DEC_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_DEC(cpu, mem[eadr]);


}


/*
  opname:  CLD
  opcode:  0xD8 
  example: CLD 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :---0---
  bytes: 1 
  
*/

void cpu_6502_CLD_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_CLD(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xD9 
  example: CMP $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_CMP_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  CMP
  opcode:  0xDD 
  example: CMP $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_CMP_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_CMP(cpu, mem[eadr]);


}


/*
  opname:  DEC
  opcode:  0xDE 
  example: DEC $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_DEC_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_DEC(cpu, mem[eadr]);


}


/*
  opname:  CPX
  opcode:  0xE0 
  example: CPX #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CPX_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_CPX(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xE1 
  example: SBC ($A5,X)
  adr:  indirect X-indexed zero page; ea = mem[zpadr+X|zpadr+X+1]
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_SBC_izx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izx_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  CPX
  opcode:  0xE4 
  example: CPX $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----**
  bytes: 2 
  
*/

void cpu_6502_CPX_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_CPX(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xE5 
  example: SBC $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_SBC_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  INC
  opcode:  0xE6 
  example: INC $AB
  adr:  zero page ; ea = zpadr
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_INC_zp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zp_adr_mode(cpu, mem);
  do_INC(cpu, mem[eadr]);


}


/*
  opname:  INX
  opcode:  0xE8 
  example: INX 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :*----*-
  bytes: 1 
  
*/

void cpu_6502_INX_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_INX(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xE9 
  example: SBC #$AB    
  adr:  immediate -- data immediate after opcode; data = mem[PC+1]
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_SBC_imm(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imm_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  NOP
  opcode:  0xEA 
  example: NOP 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :-------
  bytes: 1 
  
*/

void cpu_6502_NOP_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_NOP(cpu, mem[eadr]);


}


/*
  opname:  CPX
  opcode:  0xEC 
  example: CPX $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----**
  bytes: 3 
  
*/

void cpu_6502_CPX_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_CPX(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xED 
  example: SBC $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_SBC_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  INC
  opcode:  0xEE 
  example: INC $ABCD
  adr:  absolute 16 bit address; data = mem[abs_high|abs_low]
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_INC_abs(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abs_adr_mode(cpu, mem);
  do_INC(cpu, mem[eadr]);


}


/*
  opname:  BEQ
  opcode:  0xF0 
  example: BEQ $AB
  adr:  relativ; address is relativ with 8-bit signed offset to PC; adr=pc+offset
  flags:    NVBDIZC :-------
  bytes: 2 
  
*/

void cpu_6502_BEQ_rel(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = rel_adr_mode(cpu, mem);
  do_BEQ(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xF1 
  example: SBC ($A5),X
  adr:  indirect Y-indexed zero page; ea = mem[zpadr|zpadr+1]+Y
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_SBC_izy(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = izy_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xF5 
  example: SBC $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :**---**
  bytes: 2 
  
*/

void cpu_6502_SBC_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  INC
  opcode:  0xF6 
  example: INC $AB,X
  adr:  zero page with index register X; ea = zpadr+X
  flags:    NVBDIZC :*----*-
  bytes: 2 
  
*/

void cpu_6502_INC_zpx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = zpx_adr_mode(cpu, mem);
  do_INC(cpu, mem[eadr]);


}


/*
  opname:  SED
  opcode:  0xF8 
  example: SED 
  adr:  implizit; no additional info needed
  flags:    NVBDIZC :---1---
  bytes: 1 
  
*/

void cpu_6502_SED_imp(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = imp_adr_mode(cpu, mem);
  do_SED(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xF9 
  example: SBC $ABCD,Y
  adr:  absolute 16 bit address with index Y; ea = abs+Y
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_SBC_aby(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = aby_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  SBC
  opcode:  0xFD 
  example: SBC $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :**---**
  bytes: 3 
  
*/

void cpu_6502_SBC_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_SBC(cpu, mem[eadr]);


}


/*
  opname:  INC
  opcode:  0xFE 
  example: INC $ABCD,X
  adr:  absolute indexed addressing -- absolute 16 bit address with index X; ea = abs+X
  flags:    NVBDIZC :*----*-
  bytes: 3 
  
*/

void cpu_6502_INC_abx(struct _6510_cpu* cpu, char mem[][9]){
  int eadr = abx_adr_mode(cpu, mem);
  do_INC(cpu, mem[eadr]);


}



void imp_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void imm_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){} 
 void rel_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void izx_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void izy_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void zp_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void zpx_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void zpy_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void abs_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void abx_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){}
 void aby_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){} 
 void ind_adr_mode(struct _6510_cpu* cpu, char memory[][9] ){} 
void cpu_6502_illegal(struct _6510_cpu* cpu, char memory[][9] ){}
 